apiVersion: v1
kind: Pod
metadata:
  name: my-app-secret-pod-env
spec:
  containers:
  - name: my-secret-container
    image: busybox
    command: ["sh", "-c", "echo Username: $DB_USERNAME && echo Password: $DB_PASSWORD && sleep 3600"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: password
