apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  volumes:
  - name: shared-data-volume
    emptyDir: {}
  containers:
  - name: writer-container
    image: busybox
    command: ["sh", "-c", "echo 'Hello from writer container' >> /opt/shared/data.txt && sleep 3600"]
    volumeMounts:
    - name: shared-data-volume
      mountPath: /opt/shared
  - name: reader-container
    image: busybox
    command: ["sh", "-c", "sleep 10 && cat /opt/shared/data.txt && sleep 3600"]
    volumeMounts:
    - name: shared-data-volume
      mountPath: /opt/shared
