apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc-pod
spec:
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: data-volume
          mountPath: "/usr/share/nginx/html"
  nodeSelector:
    kubernetes.io/hostname: node1
